import Head from "next/head";
import Image from "next/legacy/image";
import HeaderComponent from "@/components/common/header";

export default function About() {
    return (
    <div>
        <Head>
            <title>William Liu | About Me</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-slate-200 min-h-screen min-w-fit">
            <HeaderComponent />
            <div className="flex flex-row justify-around px-14">
                <div className="flex flex-col justify-start p-10">
                    <h2 className="text-5xl py-2 font-medium text-slate-800">About Me</h2>
                    <p className="text-lg text-slate-800">Hello! I'm a student at Western University studying Computer Science. I'm someone who's passionate 
                    about learning and creating, combining an analytical mind with creative aspirations. Some of my hobbies include <span className="text-blue-700 font-medium">learning languages</span>, <span className="text-blue-700 font-medium">graphic design</span>, and <span className="text-blue-700 font-medium">cooking</span>.</p>
                </div>
                <div>
                </div>
            </div>
        </main>
    </div>
    )
}
