import Head from "next/head";
import Image from "next/legacy/image";
import HeaderWhiteComponent from "@/components/common/headerwhite";
import phones from "../../public/phones.png";

export default function About() {
    return (
    <div>
        <Head>
            <title>William Liu | CookEasy</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
        </Head>
        <main className="bg-gradient-to-b from-slate-200 to-slate-100 min-h-screen min-w-fit font-sans">
            <div className="bg-gradient-to-b from-green-600 to-lime-500 pb-20 sm:pb-50">
                <HeaderWhiteComponent />
                <div className="flex flex-col lg:flex-row justify-around mx-5 sm:mx-20">
                    <div className="flex shrink flex-col justify-center p-10">
                        <h2 className="text-5xl font-semibold text-white py-2">CookEasy</h2>
                        <p className="text-xl font-semibold text-white pt-4">Timeline: <span className="font-normal">February 2023 (4 days; design sprint)</span></p>
                        <p className="text-xl font-semibold text-white pt-4">Type: <span className="font-normal">App design, personal project</span></p>
                        <p className="text-xl font-semibold text-white pt-4">Tools: <span className="font-normal">Figma</span></p>
                    </div>
                    <div className="h-fill w-96 md:w-[28rem] lg:w-[32rem] xl:w-[48rem] relative sm:pt-15">
                        <Image src={phones} />
                    </div>
                </div>
            </div>
            <div className="flex justify-start mx-5 p-3 sm:mx-20 sm:p-10 md:mx-36 md:p-14">
                <div className="flex flex-col justify-center text-left">
                    <h2 className="text-left text-5xl py-5 font-medium text-slate-800">Background Information</h2>
                    <h3 className="text-left text-3xl py-3 font-medium text-slate-800">Overview</h3>
                    <p className="text-left text-xl py-2 font-normal text-slate-800 leading-10">A common issue that many people encounter in their day-to-day lives that many 
                    people face is the challenge of cooking on a consistent basis. Especially given busy schedules and the significant effort required to plan out and cook 
                    meals, many have resorted to eating out rather than cooking for themselves. Given that eating out can often be expensive and unhealthy, I wanted to develop 
                    a solution that was able to address the difficulties of cooking regularly.</p>
                    <p className="text-left text-xl py-2 font-normal text-slate-800 leading-10">Upon conducting research & user interviews, I found some of the key insights to 
                    consider when tackling this issue to be:</p>
                    <p className="text-left text-xl pl-5 pt-10 pb-3 font-normal text-slate-600 leading-10"><span className="text-green-600 font-semibold">1. </span>Cooking (considering 
                    kitchen prep/cleaning & cooking time) often requires significant investment in time and energy when done consistently.</p>
                    <p className="text-left text-xl pl-5 py-3 font-normal text-slate-600 leading-10"><span className="text-green-600 font-semibold">2. </span>Finding recipes when 
                    planning out meals while attempting to maintain variety introduces additional barriers to cooking on a regular basis.</p>
                    <p className="text-left text-xl pl-5 py-3 font-normal text-slate-600 leading-10"><span className="text-green-600 font-semibold">3. </span>Buying groceries can
                    be inconvenient, especially for people with busy schedules, and can be a major deterrent to at-home cooking. </p>
                    <p className="text-left text-xl pl-5 pt-3 pb-10 font-normal text-slate-600 leading-10"><span className="text-green-600 font-semibold">4. </span>Considering health and
                    nutritional needs in meal planning further complicates the process of planning meals. </p>
                    <p className="text-left text-xl py-2 font-normal text-slate-800 leading-10"><span className="font-semibold">Problem Statement: </span> People experience considerable
                    difficulties with cooking at home consistently and need a way to more easily complete the meal planning process.</p>
                </div>
            </div>
        </main>
    </div>
    )
}
