import Head from "next/head";
import Image from "next/legacy/image";
import HeaderWhiteComponent from "@/components/common/headerwhite";
import phones from "../../public/phones.png";

export default function About() {
    return (
    <div>
        <Head>
            <title>William Liu | About Me</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
        </Head>
        <main className="bg-gradient-to-b from-slate-200 to-slate-100 min-h-screen min-w-fit font-sans">
            <div className="bg-gradient-to-b from-green-600 to-lime-500 pb-20 sm:pb-50">
                <HeaderWhiteComponent />
                <div className="flex flex-col lg:flex-row justify-around mx-5 sm:mx-20">
                    <div className="flex shrink flex-col justify-center p-10">
                        <h2 className="text-5xl font-semibold text-white py-2">CookEasy</h2>
                        <p className="text-xl font-semibold text-white pt-4">Timeline: <span className="font-normal">February 2023 (4 days; design sprint)</span></p>
                        <p className="text-xl font-semibold text-white pt-4">Type: <span className="font-normal">App design, personal project</span></p>
                        <p className="text-xl font-semibold text-white pt-4">Tools: <span className="font-normal">Figma</span></p>
                    </div>
                    <div className="h-fill w-96 md:w-[28rem] lg:w-[32rem] xl:w-[48rem] relative sm:pt-15">
                        <Image src={phones} />
                    </div>
                </div>
            </div>
            <div className="flex justify-start mx-5 p-3 sm:mx-20 sm:p-10">
                <div className="flex flex-col justify-center text-left">
                    <p>TBA!</p>
                </div>
            </div>
        </main>
    </div>
    )
}
