import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillMail, AiFillLinkedin, AiFillGithub} from "react-icons/ai";
import Image from "next/legacy/image";
import profile from "../../public/profile.png"
import logo from "../../public/logo.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>William Liu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-175 px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <Image src={logo} height="48px" width="48px" />
            <ul className="flex items-center gap-8">
              <li><a className="group text-xl font-medium text-slate-800 transition duration-200" href="#">About Me<span className="block max-w-0 group-hover:max-w-full transition-all duration-300 h-0.5 bg-blue-700"></span></a></li>
              <li><a className="group text-xl font-medium text-slate-800 transition duration-200" href="#">Blog<span className="block max-w-0 group-hover:max-w-full transition-all duration-300 h-0.5 bg-blue-700"></span></a></li>
              <li><a className="group text-xl font-medium text-slate-800 transition duration-200" href="#">Work<span className="block max-w-0 group-hover:max-w-full transition-all duration-300 h-0.5 bg-blue-700"></span></a></li>
              <li><a className="group text-xl font-medium text-slate-800 transition duration-200" href="#">Resume<span className="block max-w-0 group-hover:max-w-full transition-all duration-300 h-0.5 bg-blue-700"></span></a></li>
            </ul>
          </nav>
          <div className="flex flex-row justify-center">
            <div className="mx-10 flex flex-col justify-center text-left p-10">
              <div>
                <h2 className="text-5xl py-2 font-medium">Hi, I'm <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-700 to-blue-500">William</span>.</h2>
                <p className="text-md py-5 leading-8 text-slate-800">I'm a developer and designer focused on creating seamless experiences through software.</p>
              </div>
              <div className="text-5xl flex justify-start gap-16">
                <a href="mailto:liu.wllm@gmail.com" target="_blank" className="text-slate-600 hover:text-blue-700"><AiFillMail className="cursor-pointer" /></a>
                <a href="https://www.linkedin.com/in/liuwllm" target="_blank" className="text-slate-600 hover:text-blue-700"><AiFillLinkedin className="cursor-pointer" /></a>
                <a href="https://www.github.com/liuwllm" target="_blank" className="text-slate-600 hover:text-blue-700"><AiFillGithub className="cursor-pointer" /></a>
              </div>
            </div>
            <div className="grow-0 shrink-0 mx-10 relative rounded-full w-80 h-80 rotate-2 overflow-hidden ">
              <Image src={profile} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>

        </section>
      </main>
    </div>
  );
}
